return {
 ["name:Arial/B:mode=node;script=latn;language=dflt;#b#786433"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;#b#786434"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#1132462"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#1630536"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#327680"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#393216"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#458752"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#524288"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#655360"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#717619"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#786432"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#943718"]={ "/System/Library/Fonts/Supplemental/Arial Bold.ttf", false },
 ["name:Arial/BI:mode=node;script=latn;language=dflt;#bi#786433"]={ "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf", false },
 ["name:Arial/BI:mode=node;script=latn;language=dflt;#bi#786434"]={ "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;#i#786433"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;#i#786434"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;+tlig;#i#393216"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;+tlig;#i#524288"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;+tlig;#i#655360"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;+tlig;#i#717619"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;+tlig;#i#786432"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;+tlig;#i#943718"]={ "/System/Library/Fonts/Supplemental/Arial Italic.ttf", false },
 ["name:Arial:mode=node;#786430"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;#786434"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;#786433"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;#786434"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#1132462"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#1359217"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#1630536"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#327680"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#393216"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#458752"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#524288"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#786432"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#943718"]={ "/System/Library/Fonts/Supplemental/Arial.ttf", false },
}